apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexustest-ai.apiServiceName" . }}
  labels:
    {{- include "nexustest-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
    {{- if .Values.api.metrics.enabled }}
    - name: metrics
      port: {{ .Values.api.metrics.port }}
      targetPort: {{ .Values.api.metrics.port }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "nexustest-ai.name" . }}
    app.kubernetes.io/component: api
