{{- if and .Values.config.create (not .Values.config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexustest-ai.configMapName" . }}
  labels:
    {{- include "nexustest-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ tpl (printf "%v" $value) $ | quote }}
  {{- end }}
{{- end }}
