{{- if and .Values.redis.enabled .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-credentials" (include "nexustest-ai.redisName" .) }}
  labels:
    {{- include "nexustest-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
{{- end }}
