{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
{{- $dbUrl := tpl (default "" (index .Values.secrets.stringData "DATABASE_URL")) . -}}
{{- $redisUrl := tpl (default "" (index .Values.secrets.stringData "REDIS_URL")) . -}}
{{- if and (not $dbUrl) (.Values.postgresql.externalUrl) }}
{{- $dbUrl = tpl .Values.postgresql.externalUrl . -}}
{{- end -}}
{{- if and (not $redisUrl) (.Values.redis.externalUrl) }}
{{- $redisUrl = tpl .Values.redis.externalUrl . -}}
{{- end -}}
{{- if and (not $dbUrl) (.Values.postgresql.enabled) }}
{{- $dbUser := tpl (printf "%v" .Values.postgresql.auth.username) . -}}
{{- $dbPass := tpl (printf "%v" .Values.postgresql.auth.password) . -}}
{{- $dbName := tpl (printf "%v" .Values.postgresql.auth.database) . -}}
{{- $dbHost := printf "%s" (include "nexustest-ai.postgresqlName" .) -}}
{{- $dbPort := int .Values.postgresql.service.port -}}
{{- $dbUrl = printf "postgresql://%s:%s@%s:%d/%s" (urlquery $dbUser) (urlquery $dbPass) $dbHost $dbPort $dbName -}}
{{- end -}}
{{- if and (not $redisUrl) (.Values.redis.enabled) }}
{{- $redisHost := printf "%s" (include "nexustest-ai.redisName" .) -}}
{{- $redisPort := int .Values.redis.service.port -}}
{{- if .Values.redis.password }}
{{- $redisPass := tpl (printf "%v" .Values.redis.password) . -}}
{{- $redisUrl = printf "redis://:%s@%s:%d/0" (urlquery $redisPass) $redisHost $redisPort -}}
{{- else -}}
{{- $redisUrl = printf "redis://%s:%d/0" $redisHost $redisPort -}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexustest-ai.secretName" . }}
  labels:
    {{- include "nexustest-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{- if and (ne $key "DATABASE_URL") (ne $key "REDIS_URL") }}
  {{ $key }}: {{ tpl (printf "%v" $value) . | quote }}
  {{- end }}
  {{- end }}
  {{- if $dbUrl }}
  DATABASE_URL: {{ $dbUrl | quote }}
  {{- end }}
  {{- if $redisUrl }}
  REDIS_URL: {{ $redisUrl | quote }}
  {{- end }}
{{- end }}
