name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pre-commit pytest

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t api-automation-backend ./backend
