name: Security Scan

on:
  push:
  pull_request:

jobs:
  sast-deps:
    name: Python SAST and Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install bandit pip-audit

      - name: Run Bandit
        run: |
          bandit -r backend/app -x backend/tests -f json -o bandit-report.json || true

      - name: Run pip-audit
        run: |
          pip-audit -r backend/requirements.txt -f json -o pip-audit.json || true

      - name: Upload SAST artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            bandit-report.json
            pip-audit.json

  container-scan:
    name: Container image scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t local/backend:scan ./backend

      - name: Build frontend image
        run: |
          if [ -f ./frontend/Dockerfile ]; then
            docker build -t local/frontend:scan ./frontend
          else
            echo "No frontend Dockerfile, skipping"
          fi

      - name: Trivy scan backend
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: local/backend:scan
          format: 'sarif'
          output: 'trivy-backend.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Trivy scan frontend
        if: ${{ hashFiles('frontend/Dockerfile') != '' }}
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: local/frontend:scan
          format: 'sarif'
          output: 'trivy-frontend.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Upload Trivy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-backend.sarif
            trivy-frontend.sarif
